version: 3
workdir: .
allow:
  depOnAnyVendor: false
vendors:
  cobra:
    in: github.com/spf13/cobra
  resty:
    in: resty.dev/v3
  testify:
    in: github.com/stretchr/testify/**
  httpmock:
    in: github.com/jarcoal/httpmock
components:
  cmd:
    in: cmd/**
  bootstrap:
    in: internal
  components:
    in: internal/components
  paint:
    in: internal/paint
  reports:
    in: internal/reports
  contractfiles:
    in: internal/contractfiles
  features:
    in: internal/features/*
  tests:
    in: tests/**
deps:
  cmd:
    mayDependOn:
      - bootstrap
  bootstrap:
    mayDependOn:
      - components
      - paint
      - reports
      - features
    canUse:
      - cobra
      - testify
  features:
    mayDependOn:
      - components
      - paint
      - reports
      - contractfiles
    canUse:
      - cobra
      - testify
  components:
    canUse:
      - resty
  paint:
    mayDependOn:
      - components
  reports:
    mayDependOn:
      - paint
    canUse:
      - testify
  tests:
    anyProjectDeps: true
    canUse:
      - testify
      - httpmock
